# Create environment:
# $ conda env create --force
name: gmm
channels:
  - conda-forge
dependencies:
  - python = 3.6
  - ipython
  - jupyter
  - numpy
  - scikit-learn
  - pandas
  - plotly
    
# Start environment:
# $ source activate gmm